//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    
    public partial class BomBase
    {
        public int BomID { get; set; }
        public string BomCode { get; set; }
        public string BomName { get; set; }
        public string BomReference { get; set; }
    }
}
