//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    
    public partial class CommodityMaterialBase
    {
        public int CommodityMaterialID { get; set; }
        public string CommodityMaterialCode { get; set; }
        public string CommodityMaterialReference { get; set; }
        public string CommodityMaterialName { get; set; }
    }
}
