//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    
    public partial class MaterialIssuePendingPlannedOrder
    {
        public int MaterialIssueTypeID { get; set; }
        public int PlannedOrderID { get; set; }
        public string PlannedOrderCode { get; set; }
        public int WorkshiftID { get; set; }
        public string WorkshiftCode { get; set; }
        public int ProductionOrderDetailID { get; set; }
        public int ProductionOrderID { get; set; }
        public int PlannedOrderDetailID { get; set; }
        public int CustomerID { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public int CommodityID { get; set; }
        public string CommodityCode { get; set; }
        public int ProductionLineID { get; set; }
        public string ProductionLineCode { get; set; }
        public int MoldID { get; set; }
        public string MoldCode { get; set; }
        public string PlannedOrderReference { get; set; }
        public System.DateTime PlannedOrderEntryDate { get; set; }
    }
}
