//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    
    public partial class MaterialIssuePendingPlannedOrderDetail
    {
        public int CommodityID { get; set; }
        public string CommodityCode { get; set; }
        public string CommodityName { get; set; }
        public int CommodityTypeID { get; set; }
        public Nullable<int> GoodsReceiptDetailID { get; set; }
        public Nullable<decimal> PlannedOrderRemains { get; set; }
        public decimal WorkingHours { get; set; }
        public decimal CyclePerHours { get; set; }
        public decimal MoldQuantity { get; set; }
        public int Quantity { get; set; }
        public Nullable<bool> IsSelected { get; set; }
        public Nullable<int> GoodsReceiptID { get; set; }
        public Nullable<System.DateTime> GoodsReceiptEntryDate { get; set; }
        public string GoodsReceiptReference { get; set; }
        public string GoodsReceiptCode { get; set; }
        public int PlannedOrderMaterialID { get; set; }
        public decimal BlockUnit { get; set; }
        public decimal BlockQuantity { get; set; }
        public Nullable<decimal> QuantityAvailables { get; set; }
    }
}
