//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    
    public partial class PlannedOrderViewDetail
    {
        public int PlannedOrderDetailID { get; set; }
        public int PlannedOrderID { get; set; }
        public int CommodityID { get; set; }
        public string CommodityCode { get; set; }
        public string CommodityName { get; set; }
        public int CommodityTypeID { get; set; }
        public int MoldID { get; set; }
        public string MoldCode { get; set; }
        public Nullable<int> VoidTypeID { get; set; }
        public string VoidTypeCode { get; set; }
        public string VoidTypeName { get; set; }
        public Nullable<int> VoidClassID { get; set; }
        public bool InActivePartial { get; set; }
        public Nullable<System.DateTime> InActivePartialDate { get; set; }
        public string Remarks { get; set; }
        public int CommodityMaterialID { get; set; }
        public string CommodityMaterialCode { get; set; }
        public string CommodityMaterialName { get; set; }
        public decimal Quantity { get; set; }
    }
}
