//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SemifinishedProductDetail
    {
        public int SemifinishedProductDetailID { get; set; }
        public int SemifinishedProductID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public int LocationID { get; set; }
        public int ProductionOrderID { get; set; }
        public int ProductionOrderDetailID { get; set; }
        public int MaterialIssueID { get; set; }
        public int MaterialIssueDetailID { get; set; }
        public int FirmOrderDetailID { get; set; }
        public int FirmOrderID { get; set; }
        public int GoodsReceiptDetailID { get; set; }
        public Nullable<int> SemifinishedHandoverID { get; set; }
        public int CommodityID { get; set; }
        public int CommodityTypeID { get; set; }
        public int SalespersonID { get; set; }
        public decimal Quantity { get; set; }
        public decimal QuantityWastage { get; set; }
        public decimal QuantityFailure { get; set; }
        public decimal QuantityRejected { get; set; }
        public decimal QuantityRejectedReturned { get; set; }
        public string Remarks { get; set; }
        public bool Approved { get; set; }
    
        public virtual Commodity Commodity { get; set; }
        public virtual ProductionOrderDetail ProductionOrderDetail { get; set; }
        public virtual ProductionOrder ProductionOrder { get; set; }
        public virtual SemifinishedProduct SemifinishedProduct { get; set; }
        public virtual MaterialIssueDetail MaterialIssueDetail { get; set; }
    }
}
